Fix calculation of expiration timestamp
jenkinsci/oic-auth-plugin pull request #359
Opened 2024-07-30 13:50 UTC by mprausa

`currentTimestamp` is in millis already which is why it should not be mulitplied by 1000.

The constructor of `OicCredentials` is called with `CLOCK.millis()` ([here](https://github.com/jenkinsci/oic-auth-plugin/blob/master/src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java#L1000) and [here](https://github.com/jenkinsci/oic-auth-plugin/blob/master/src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java#L1490)) for the `currentTimestamp` parameter which shows that `currentTimestamp` is indeed in millis and not seconds.

This bug was introduced in bba32e09 (PR #357).

### Testing done

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-07-30 14:09 UTC, mprausa commented
I've added a second commit. I think the other change on the same line done in PR #357 is incorrect as well. We have to subtract `allowedClockSkewFixed`, so that  the token is refreshed earlier not later.

2024-08-15 12:27 UTC, mikecirioli commented on src/main/java/org/jenkinsci/plugins/oic/OicCredentials.java
> +            this.expiresAtMillis = currentTimestamp + (expiresInSeconds - allowedClockSkewFixed) * 1000;
shouldn't the `allowedClockSkewFixed` be added to `expiresInSeconds`?   I thought its purpose was to add some extra padding to the expiration check to allow for slightly mismatched clocks?

2024-08-27 21:37 UTC, michael-doubez requested changes
Clock skew is a tolerance on the detection of expired token.

> A JWT is considered to be valid within 5 minutes of the exp, nbf, and iat claims. You can configure this value on the clockSkew attribute.

I understand it as extending the life time of a token:
- valid after nbf-skew
- valid before exp+skew
- token not generated in the future if greater than iat-skew.

On that matter `expiresInSeconds + allowedClockSkew` looks right.

2024-08-28 07:57 UTC, mprausa commented
@michael-doubez Yes, I agree. I've removed the second commit.

2024-08-28 09:19 UTC, michael-doubez approved these changes
LGTM

2024-08-28 09:19 UTC, merged